### ISSUE TITLE
Pull upstream changes

### ISSUE THREAD

**Issue by rach-id** [celestiaorg/bdjuno#12]
BDJuno hasn't been following upstream changes.  These need to be pulled to be up to date.

**Comment by lzrscg** [comment]
this is done, however, the dependency issues are not resolved as discussed elsewhere. it currently won't build

**Comment by rach-id** [comment]
Try depending on this commit for Celestia-app: `60800467b1a3bfb8e81367891863f43394b2252d`  it should solve the problem
