### ISSUE TITLE
Fix testnet/mainnet config to reflect the correct `celes`/`uceles` units

### ISSUE THREAD

**Issue by rach-id** [celestiaorg/bdjuno#7]
Currently, our deployment of BDJuno uses `celes` and `uceles` interchangeably. This is due to a confusion in the `devnet-2` genesis file generation, where the units are not properly defined.
In upcoming networks, we will have a correct genesis and thus the configuration in the README will need to be updated to reflect the correct changes.

**Comment by lzrscg** [comment]
done
